apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: highload-service-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: highload.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: highload-service
            port:
              number: 8080
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: highload-service
            port:
              number: 8080

