apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: highload-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  # scrape Services in the `default` namespace
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: highload-service
  endpoints:
    - port: http
      path: /prometheus
      interval: 15s
      scrapeTimeout: 10s

