global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'highload-service'
    static_configs:
      - targets: ['highload-service:8080']
    metrics_path: '/prometheus'
    scrape_interval: 5s

